
spring:
  security:
    oauth2:
     client:
      registration:
       google:
        client-id: 650109837523-vcpbjogn6rgu2g4k1gojsfc5rtm5i7iq.apps.googleusercontent.com
        client-secret: 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
        scope:
          - email
          - profile